// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEEGl0rzR27OYrE9J--lcoQs3UolZMVlY',
    appId: '1:823109031805:web:bf79f0a10db08009295e14',
    messagingSenderId: '823109031805',
    projectId: 'moneycontroljustaman045',
    authDomain: 'moneycontroljustaman045.firebaseapp.com',
    storageBucket: 'moneycontroljustaman045.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKlfOviJ6JFLW2BaLDlVblHqcqbDgIaUc',
    appId: '1:823109031805:android:9fb6d047fc753301295e14',
    messagingSenderId: '823109031805',
    projectId: 'moneycontroljustaman045',
    storageBucket: 'moneycontroljustaman045.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaxiqIIIk47tzp1IuKhJMTZaals3FR1DU',
    appId: '1:823109031805:ios:b4d3c7df3af6e83f295e14',
    messagingSenderId: '823109031805',
    projectId: 'moneycontroljustaman045',
    storageBucket: 'moneycontroljustaman045.firebasestorage.app',
    iosBundleId: 'app.vercel.justaman045.moneyControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaxiqIIIk47tzp1IuKhJMTZaals3FR1DU',
    appId: '1:823109031805:ios:b4d3c7df3af6e83f295e14',
    messagingSenderId: '823109031805',
    projectId: 'moneycontroljustaman045',
    storageBucket: 'moneycontroljustaman045.firebasestorage.app',
    iosBundleId: 'app.vercel.justaman045.moneyControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEEGl0rzR27OYrE9J--lcoQs3UolZMVlY',
    appId: '1:823109031805:web:170738853189d013295e14',
    messagingSenderId: '823109031805',
    projectId: 'moneycontroljustaman045',
    authDomain: 'moneycontroljustaman045.firebaseapp.com',
    storageBucket: 'moneycontroljustaman045.firebasestorage.app',
  );
}
